spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matriculacion?createDatabaseIfNotExist=true
    username: root  
    password: toor
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true

  # Habilitar la carga de archivos multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB   # Tama침o m치ximo permitido para cada archivo
      max-request-size: 10MB  # Tama침o m치ximo permitido para toda la solicitud (incluyendo todos los archivos)

logging:
  file:
    name: matriculacion.log
  level:
    root: info
    es.iesjandula.matriculas_horarios_server: debug